name: CI

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+

env:
  IMAGE_NAME: ${{ secrets.DOCKER_LOGIN }}/tcommerce-web-client

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build and push the Docker image (multistage)
      env:
        IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
      run: |
        echo "${IMAGE_TAG}"
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

        docker pull ${IMAGE_NAME}:builder
        docker pull ${IMAGE_NAME}:latest

        echo "${IMAGE_TAG}"

        docker build \
          --target builder \
          --cache-from ${IMAGE_NAME}:builder \
          -t ${IMAGE_NAME}:builder \
          .
        docker build \
          --cache-from ${IMAGE_NAME}:latest \
          --cache-from ${IMAGE_NAME}:builder \
          -t ${IMAGE_NAME}:latest \
          -t ${IMAGE_NAME}:${IMAGE_TAG} \
          .

        docker push ${IMAGE_NAME}:builder
        docker push ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:${IMAGE_TAG}

  deploy:
    needs: build-push

    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2s
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          passphrase: ${{ secrets.SERVER_SSH_PRIVATE_KEY_PASSPHRASE }}
          script: |
            whoami
            ls -la
